
name: Deploy to modal

on:
  push:
    # branches: [ main ]

jobs:
  modal-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: login to modal
        run: |
            modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: deploy stub
        run: |
          modal deploy --name ${{ secrets.MODAL_APP_NAME}} cron.py
